<a href="https://colab.research.google.com/github/1EdwinVargas/Cursoplatzimachinepython/blob/master/CursoMACHINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [12]:
a1 = np.array([1,2,3])
type (a1)

numpy.ndarray

In [13]:
a2 = np.arange(10)
a2 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a3 = np.zeros((3,3))
a4 = np.ones((3,3))

In [18]:
from IPython.display import display
display(a3);display(a4)
 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.linspace(a,b,n) es una funcion que permite crear arrays de una dimension , de largo n y que contiene puntos entre a y b distanciados de forma regular.la distancia entre cada punto sera de (b-a)/(n-1)