<a href="https://colab.research.google.com/github/1EdwinVargas/Cursoplatzimachinepython/blob/master/CursoMACHINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

### ***Dimension de un array***

In [19]:
a1 = np.array([1,2,3]) # Transforma una lista en array
type (a1)

numpy.ndarray

In [13]:
a2 = np.arange(10) # crea un range de lista tipo array 
a2 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a3 = np.zeros((3,3)) # crea un array lleno de ceros
a4 = np.ones((3,3))  # crea un array lleno de unos

In [24]:
from IPython.display import display  # esta funcion permite ver el tipo de la variable "array" 
display(a3);display(a4)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.linspace(a,b,n) es una funcion que permite crear arrays de una dimension , de largo n y que contiene puntos entre a y b distanciados de forma regular.la distancia entre cada punto sera de (b-a)/(n-1)

In [34]:
a5 = np.linspace(0,1,15)
display (a5)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [35]:
# dtypes
a5.dtype

dtype('float64')

El comando Shape se usa para verificar u optener el tamaño o dimension del array 

In [0]:
a3.shape 

In [42]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [43]:
# verificar si los dos array iguales
np.array_equal(a1D,a2D)

False

In [0]:
# reshaping para cambiar el tamaño de los array no funciona con todos 
new_dims =(1,a1D.shape[0])
a = a1D.reshape(new_dims)


### ***Acceder a elementos y slicing***

In [46]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a


array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [54]:
a[2,0]

6

In [56]:
a = np.arange(10)
b = np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
a[:5]

array([0, 1, 2, 3, 4])

In [61]:
b[0:3,2] #sintaxis para acceder a las filas

array([0., 0., 1.])

In [59]:
b[2,0:3] # sintaxis para acceder a las colomnas

array([0., 0., 1.])

In [62]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ***Operaciones con array **

In [68]:
a = np.arange(4)
a
print("a     =", a     )
print("a + 5 =", a + 5)
print("a - 2 =", a - 2)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a// 2 =", a //2)
print("-a    =", -a   )
print("a **2 =", a **2)
print("a % 2 =", a%  2)


a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 2 = [-2 -1  0  1]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a// 2 = [0 0 1 1]
-a    = [ 0 -1 -2 -3]
a **2 = [0 1 4 9]
a % 2 = [0 1 0 1]
